### PR TITLE
Fixes the command used to add the pulp user to the wheel group.

### LINKED ISSUE #93: root power being required by some tests
Some tests require root permissions for specific file operations.

The easiest(not the right) way to solve this is adding the pulp user to the sudoers file with NOPASSWD or adding the pulp user to the `sudo` group.

Using #68 as an epic.

### PR DESCRIPTION
**Pull request by decko**
Closes #93

### CODE REVIEW

**Review by lubosmj — APPROVED** [review]

File: base/init.sh [hunk 1]
```diff
@@ -20,4 +20,4 @@ echo 'Defaults    env_keep += "DJANGO_SETTINGS_MODULE PULP_SETTINGS XDG_CONFIG_H
 
 # Add user pulp to sudoers so tests can use sudo
 echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/nopasswd
-echo 'usermod -a -G wheel pulp'
```
Comment (ggainey) [inline base/init.sh:23]: :facepalm: oh dear

**Review by ggainey — APPROVED** [review]

**Review by dkliban — APPROVED** [review]
